const fs = require('fs');
const colors = require('colors');

const defaultAPIUrl = 'https://live.api.edualert.ro';

const directory = './src/environments';
const filename = 'environment.ts';
const filePath = `${directory}/${filename}`;

const fileContent = `// File automatically generated by ./set-env.js

export const environment = {
   apiUrl: '${process.env.API_URL || defaultAPIUrl}',
   production: ${process.env.PRODUCTION || false}
};
`;

createDir(directory);
createFile(filePath, fileContent);


function createDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir);
  }
}

function createFile(path, content) {
  fs.writeFile(path, content, function (err) {
    if (err) {
      throw console.error(err);
    } else {
      console.log(`Angular ${colors.brightBlue(`environment.ts`)} file generated correctly at ${colors.brightBlue(path)}:`);
      console.log(colors.yellow(content));
    }
  });
}
