const fs = require('fs');
const colors = require('colors');

// Configure Angular `environment.ts` file path
const targetPath = './src/environments/environment.ts';

const defaultDevApiUrl = 'https://live.api.edualert.ro';
const envConfigFile = `// File automatically generated by ./set-env.js
export const environment = {
   apiUrl: '${process.env.API_URL || defaultDevApiUrl}',
   production: ${process.env.PRODUCTION || false}
};
`;

fs.writeFile(targetPath, envConfigFile, function (err) {
  if (err) {
    throw console.error(err);
  } else {
    console.log(`Angular ${colors.brightBlue(`environment.ts`)} file generated correctly at ${colors.brightBlue(targetPath)}:`);
    console.log(colors.yellow(envConfigFile));
  }
});
